// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages.proto

package strc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	// Types that are valid to be assigned to Payload:
	//	*Message_Tx
	//	*Message_Prepare
	//	*Message_Preprepare
	//	*Message_Commit
	//	*Message_RequestAllData
	//	*Message_RequestData
	//	*Message_ResponseData
	//	*Message_Auth
	//	*Message_CmitFin
	Payload              isMessage_Payload `protobuf_oneof:"payload"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

type isMessage_Payload interface {
	isMessage_Payload()
}

type Message_Tx struct {
	Tx *Transaction `protobuf:"bytes,1,opt,name=tx,proto3,oneof"`
}

type Message_Prepare struct {
	Prepare *Prepare `protobuf:"bytes,2,opt,name=prepare,proto3,oneof"`
}

type Message_Preprepare struct {
	Preprepare *PrePrepare `protobuf:"bytes,3,opt,name=preprepare,proto3,oneof"`
}

type Message_Commit struct {
	Commit *Commit `protobuf:"bytes,4,opt,name=commit,proto3,oneof"`
}

type Message_RequestAllData struct {
	RequestAllData *RequestAllData `protobuf:"bytes,5,opt,name=requestAllData,proto3,oneof"`
}

type Message_RequestData struct {
	RequestData *RequestData `protobuf:"bytes,6,opt,name=requestData,proto3,oneof"`
}

type Message_ResponseData struct {
	ResponseData *ResponseData `protobuf:"bytes,7,opt,name=responseData,proto3,oneof"`
}

type Message_Auth struct {
	Auth *AuthHash `protobuf:"bytes,8,opt,name=auth,proto3,oneof"`
}

type Message_CmitFin struct {
	CmitFin *CommitFin `protobuf:"bytes,9,opt,name=cmitFin,proto3,oneof"`
}

func (*Message_Tx) isMessage_Payload() {}

func (*Message_Prepare) isMessage_Payload() {}

func (*Message_Preprepare) isMessage_Payload() {}

func (*Message_Commit) isMessage_Payload() {}

func (*Message_RequestAllData) isMessage_Payload() {}

func (*Message_RequestData) isMessage_Payload() {}

func (*Message_ResponseData) isMessage_Payload() {}

func (*Message_Auth) isMessage_Payload() {}

func (*Message_CmitFin) isMessage_Payload() {}

func (m *Message) GetPayload() isMessage_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *Message) GetTx() *Transaction {
	if x, ok := m.GetPayload().(*Message_Tx); ok {
		return x.Tx
	}
	return nil
}

func (m *Message) GetPrepare() *Prepare {
	if x, ok := m.GetPayload().(*Message_Prepare); ok {
		return x.Prepare
	}
	return nil
}

func (m *Message) GetPreprepare() *PrePrepare {
	if x, ok := m.GetPayload().(*Message_Preprepare); ok {
		return x.Preprepare
	}
	return nil
}

func (m *Message) GetCommit() *Commit {
	if x, ok := m.GetPayload().(*Message_Commit); ok {
		return x.Commit
	}
	return nil
}

func (m *Message) GetRequestAllData() *RequestAllData {
	if x, ok := m.GetPayload().(*Message_RequestAllData); ok {
		return x.RequestAllData
	}
	return nil
}

func (m *Message) GetRequestData() *RequestData {
	if x, ok := m.GetPayload().(*Message_RequestData); ok {
		return x.RequestData
	}
	return nil
}

func (m *Message) GetResponseData() *ResponseData {
	if x, ok := m.GetPayload().(*Message_ResponseData); ok {
		return x.ResponseData
	}
	return nil
}

func (m *Message) GetAuth() *AuthHash {
	if x, ok := m.GetPayload().(*Message_Auth); ok {
		return x.Auth
	}
	return nil
}

func (m *Message) GetCmitFin() *CommitFin {
	if x, ok := m.GetPayload().(*Message_CmitFin); ok {
		return x.CmitFin
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Message) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Message_Tx)(nil),
		(*Message_Prepare)(nil),
		(*Message_Preprepare)(nil),
		(*Message_Commit)(nil),
		(*Message_RequestAllData)(nil),
		(*Message_RequestData)(nil),
		(*Message_ResponseData)(nil),
		(*Message_Auth)(nil),
		(*Message_CmitFin)(nil),
	}
}

type CommitFin struct {
	BlockHash            []byte   `protobuf:"bytes,1,opt,name=blockHash,proto3" json:"blockHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommitFin) Reset()         { *m = CommitFin{} }
func (m *CommitFin) String() string { return proto.CompactTextString(m) }
func (*CommitFin) ProtoMessage()    {}
func (*CommitFin) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{1}
}

func (m *CommitFin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommitFin.Unmarshal(m, b)
}
func (m *CommitFin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommitFin.Marshal(b, m, deterministic)
}
func (m *CommitFin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommitFin.Merge(m, src)
}
func (m *CommitFin) XXX_Size() int {
	return xxx_messageInfo_CommitFin.Size(m)
}
func (m *CommitFin) XXX_DiscardUnknown() {
	xxx_messageInfo_CommitFin.DiscardUnknown(m)
}

var xxx_messageInfo_CommitFin proto.InternalMessageInfo

func (m *CommitFin) GetBlockHash() []byte {
	if m != nil {
		return m.BlockHash
	}
	return nil
}

type RequestAllData struct {
	DeviceId             []byte   `protobuf:"bytes,1,opt,name=deviceId,proto3" json:"deviceId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestAllData) Reset()         { *m = RequestAllData{} }
func (m *RequestAllData) String() string { return proto.CompactTextString(m) }
func (*RequestAllData) ProtoMessage()    {}
func (*RequestAllData) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{2}
}

func (m *RequestAllData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestAllData.Unmarshal(m, b)
}
func (m *RequestAllData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestAllData.Marshal(b, m, deterministic)
}
func (m *RequestAllData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestAllData.Merge(m, src)
}
func (m *RequestAllData) XXX_Size() int {
	return xxx_messageInfo_RequestAllData.Size(m)
}
func (m *RequestAllData) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestAllData.DiscardUnknown(m)
}

var xxx_messageInfo_RequestAllData proto.InternalMessageInfo

func (m *RequestAllData) GetDeviceId() []byte {
	if m != nil {
		return m.DeviceId
	}
	return nil
}

type RequestData struct {
	DeviceId             []byte   `protobuf:"bytes,1,opt,name=deviceId,proto3" json:"deviceId,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestData) Reset()         { *m = RequestData{} }
func (m *RequestData) String() string { return proto.CompactTextString(m) }
func (*RequestData) ProtoMessage()    {}
func (*RequestData) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{3}
}

func (m *RequestData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestData.Unmarshal(m, b)
}
func (m *RequestData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestData.Marshal(b, m, deterministic)
}
func (m *RequestData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestData.Merge(m, src)
}
func (m *RequestData) XXX_Size() int {
	return xxx_messageInfo_RequestData.Size(m)
}
func (m *RequestData) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestData.DiscardUnknown(m)
}

var xxx_messageInfo_RequestData proto.InternalMessageInfo

func (m *RequestData) GetDeviceId() []byte {
	if m != nil {
		return m.DeviceId
	}
	return nil
}

func (m *RequestData) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type ProofConn struct {
	Authhash             bool     `protobuf:"varint,1,opt,name=authhash,proto3" json:"authhash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProofConn) Reset()         { *m = ProofConn{} }
func (m *ProofConn) String() string { return proto.CompactTextString(m) }
func (*ProofConn) ProtoMessage()    {}
func (*ProofConn) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{4}
}

func (m *ProofConn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProofConn.Unmarshal(m, b)
}
func (m *ProofConn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProofConn.Marshal(b, m, deterministic)
}
func (m *ProofConn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProofConn.Merge(m, src)
}
func (m *ProofConn) XXX_Size() int {
	return xxx_messageInfo_ProofConn.Size(m)
}
func (m *ProofConn) XXX_DiscardUnknown() {
	xxx_messageInfo_ProofConn.DiscardUnknown(m)
}

var xxx_messageInfo_ProofConn proto.InternalMessageInfo

func (m *ProofConn) GetAuthhash() bool {
	if m != nil {
		return m.Authhash
	}
	return false
}

type ResponseData struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseData) Reset()         { *m = ResponseData{} }
func (m *ResponseData) String() string { return proto.CompactTextString(m) }
func (*ResponseData) ProtoMessage()    {}
func (*ResponseData) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{5}
}

func (m *ResponseData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseData.Unmarshal(m, b)
}
func (m *ResponseData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseData.Marshal(b, m, deterministic)
}
func (m *ResponseData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseData.Merge(m, src)
}
func (m *ResponseData) XXX_Size() int {
	return xxx_messageInfo_ResponseData.Size(m)
}
func (m *ResponseData) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseData.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseData proto.InternalMessageInfo

func (m *ResponseData) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Regist struct {
	AuthhashInfo         *AuthhashInfo `protobuf:"bytes,1,opt,name=authhashInfo,proto3" json:"authhashInfo,omitempty"`
	Auth                 *AuthHash     `protobuf:"bytes,2,opt,name=auth,proto3" json:"auth,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Regist) Reset()         { *m = Regist{} }
func (m *Regist) String() string { return proto.CompactTextString(m) }
func (*Regist) ProtoMessage()    {}
func (*Regist) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{6}
}

func (m *Regist) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Regist.Unmarshal(m, b)
}
func (m *Regist) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Regist.Marshal(b, m, deterministic)
}
func (m *Regist) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Regist.Merge(m, src)
}
func (m *Regist) XXX_Size() int {
	return xxx_messageInfo_Regist.Size(m)
}
func (m *Regist) XXX_DiscardUnknown() {
	xxx_messageInfo_Regist.DiscardUnknown(m)
}

var xxx_messageInfo_Regist proto.InternalMessageInfo

func (m *Regist) GetAuthhashInfo() *AuthhashInfo {
	if m != nil {
		return m.AuthhashInfo
	}
	return nil
}

func (m *Regist) GetAuth() *AuthHash {
	if m != nil {
		return m.Auth
	}
	return nil
}

type AuthhashInfo struct {
	DeviceId             []byte   `protobuf:"bytes,1,opt,name=deviceId,proto3" json:"deviceId,omitempty"`
	Authhash             [][]byte `protobuf:"bytes,2,rep,name=authhash,proto3" json:"authhash,omitempty"`
	Idx                  int32    `protobuf:"varint,3,opt,name=idx,proto3" json:"idx,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthhashInfo) Reset()         { *m = AuthhashInfo{} }
func (m *AuthhashInfo) String() string { return proto.CompactTextString(m) }
func (*AuthhashInfo) ProtoMessage()    {}
func (*AuthhashInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{7}
}

func (m *AuthhashInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthhashInfo.Unmarshal(m, b)
}
func (m *AuthhashInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthhashInfo.Marshal(b, m, deterministic)
}
func (m *AuthhashInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthhashInfo.Merge(m, src)
}
func (m *AuthhashInfo) XXX_Size() int {
	return xxx_messageInfo_AuthhashInfo.Size(m)
}
func (m *AuthhashInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthhashInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AuthhashInfo proto.InternalMessageInfo

func (m *AuthhashInfo) GetDeviceId() []byte {
	if m != nil {
		return m.DeviceId
	}
	return nil
}

func (m *AuthhashInfo) GetAuthhash() [][]byte {
	if m != nil {
		return m.Authhash
	}
	return nil
}

func (m *AuthhashInfo) GetIdx() int32 {
	if m != nil {
		return m.Idx
	}
	return 0
}

type AuthHash struct {
	DevicdId             []byte   `protobuf:"bytes,1,opt,name=devicdId,proto3" json:"devicdId,omitempty"`
	AuthHash             []byte   `protobuf:"bytes,2,opt,name=authHash,proto3" json:"authHash,omitempty"`
	Toggle               int32    `protobuf:"varint,3,opt,name=toggle,proto3" json:"toggle,omitempty"`
	Idx                  int32    `protobuf:"varint,4,opt,name=Idx,proto3" json:"Idx,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthHash) Reset()         { *m = AuthHash{} }
func (m *AuthHash) String() string { return proto.CompactTextString(m) }
func (*AuthHash) ProtoMessage()    {}
func (*AuthHash) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{8}
}

func (m *AuthHash) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthHash.Unmarshal(m, b)
}
func (m *AuthHash) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthHash.Marshal(b, m, deterministic)
}
func (m *AuthHash) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthHash.Merge(m, src)
}
func (m *AuthHash) XXX_Size() int {
	return xxx_messageInfo_AuthHash.Size(m)
}
func (m *AuthHash) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthHash.DiscardUnknown(m)
}

var xxx_messageInfo_AuthHash proto.InternalMessageInfo

func (m *AuthHash) GetDevicdId() []byte {
	if m != nil {
		return m.DevicdId
	}
	return nil
}

func (m *AuthHash) GetAuthHash() []byte {
	if m != nil {
		return m.AuthHash
	}
	return nil
}

func (m *AuthHash) GetToggle() int32 {
	if m != nil {
		return m.Toggle
	}
	return 0
}

func (m *AuthHash) GetIdx() int32 {
	if m != nil {
		return m.Idx
	}
	return 0
}

type Transaction struct {
	TxId                 []byte    `protobuf:"bytes,1,opt,name=TxId,proto3" json:"TxId,omitempty"`
	Data                 []byte    `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	Type                 int32     `protobuf:"varint,3,opt,name=Type,proto3" json:"Type,omitempty"`
	Auth                 *AuthHash `protobuf:"bytes,4,opt,name=auth,proto3" json:"auth,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{9}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetTxId() []byte {
	if m != nil {
		return m.TxId
	}
	return nil
}

func (m *Transaction) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Transaction) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Transaction) GetAuth() *AuthHash {
	if m != nil {
		return m.Auth
	}
	return nil
}

type Block struct {
	Hash                 []byte               `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	PrevBlockHash        []byte               `protobuf:"bytes,2,opt,name=prevBlockHash,proto3" json:"prevBlockHash,omitempty"`
	Transactions         []*Transaction       `protobuf:"bytes,3,rep,name=transactions,proto3" json:"transactions,omitempty"`
	Height               int32                `protobuf:"varint,5,opt,name=Height,proto3" json:"Height,omitempty"`
	GeneratedTime        *timestamp.Timestamp `protobuf:"bytes,6,opt,name=generatedTime,proto3" json:"generatedTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{10}
}

func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (m *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(m, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *Block) GetPrevBlockHash() []byte {
	if m != nil {
		return m.PrevBlockHash
	}
	return nil
}

func (m *Block) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

func (m *Block) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Block) GetGeneratedTime() *timestamp.Timestamp {
	if m != nil {
		return m.GeneratedTime
	}
	return nil
}

type PrePrepare struct {
	View                 uint64             `protobuf:"varint,1,opt,name=view,proto3" json:"view,omitempty"`
	PrevBlockHash        []byte             `protobuf:"bytes,2,opt,name=prevBlockHash,proto3" json:"prevBlockHash,omitempty"`
	Height               uint64             `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Txinfo               []*TransactionInfo `protobuf:"bytes,4,rep,name=txinfo,proto3" json:"txinfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *PrePrepare) Reset()         { *m = PrePrepare{} }
func (m *PrePrepare) String() string { return proto.CompactTextString(m) }
func (*PrePrepare) ProtoMessage()    {}
func (*PrePrepare) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{11}
}

func (m *PrePrepare) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrePrepare.Unmarshal(m, b)
}
func (m *PrePrepare) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrePrepare.Marshal(b, m, deterministic)
}
func (m *PrePrepare) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrePrepare.Merge(m, src)
}
func (m *PrePrepare) XXX_Size() int {
	return xxx_messageInfo_PrePrepare.Size(m)
}
func (m *PrePrepare) XXX_DiscardUnknown() {
	xxx_messageInfo_PrePrepare.DiscardUnknown(m)
}

var xxx_messageInfo_PrePrepare proto.InternalMessageInfo

func (m *PrePrepare) GetView() uint64 {
	if m != nil {
		return m.View
	}
	return 0
}

func (m *PrePrepare) GetPrevBlockHash() []byte {
	if m != nil {
		return m.PrevBlockHash
	}
	return nil
}

func (m *PrePrepare) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *PrePrepare) GetTxinfo() []*TransactionInfo {
	if m != nil {
		return m.Txinfo
	}
	return nil
}

type TransactionInfo struct {
	Transactionid        []byte   `protobuf:"bytes,1,opt,name=transactionid,proto3" json:"transactionid,omitempty"`
	TxVerify             bool     `protobuf:"varint,2,opt,name=tx_verify,json=txVerify,proto3" json:"tx_verify,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionInfo) Reset()         { *m = TransactionInfo{} }
func (m *TransactionInfo) String() string { return proto.CompactTextString(m) }
func (*TransactionInfo) ProtoMessage()    {}
func (*TransactionInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{12}
}

func (m *TransactionInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionInfo.Unmarshal(m, b)
}
func (m *TransactionInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionInfo.Marshal(b, m, deterministic)
}
func (m *TransactionInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionInfo.Merge(m, src)
}
func (m *TransactionInfo) XXX_Size() int {
	return xxx_messageInfo_TransactionInfo.Size(m)
}
func (m *TransactionInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionInfo proto.InternalMessageInfo

func (m *TransactionInfo) GetTransactionid() []byte {
	if m != nil {
		return m.Transactionid
	}
	return nil
}

func (m *TransactionInfo) GetTxVerify() bool {
	if m != nil {
		return m.TxVerify
	}
	return false
}

type Prepare struct {
	View                 uint64             `protobuf:"varint,1,opt,name=view,proto3" json:"view,omitempty"`
	Txinfo               []*TransactionInfo `protobuf:"bytes,2,rep,name=txinfo,proto3" json:"txinfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Prepare) Reset()         { *m = Prepare{} }
func (m *Prepare) String() string { return proto.CompactTextString(m) }
func (*Prepare) ProtoMessage()    {}
func (*Prepare) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{13}
}

func (m *Prepare) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Prepare.Unmarshal(m, b)
}
func (m *Prepare) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Prepare.Marshal(b, m, deterministic)
}
func (m *Prepare) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Prepare.Merge(m, src)
}
func (m *Prepare) XXX_Size() int {
	return xxx_messageInfo_Prepare.Size(m)
}
func (m *Prepare) XXX_DiscardUnknown() {
	xxx_messageInfo_Prepare.DiscardUnknown(m)
}

var xxx_messageInfo_Prepare proto.InternalMessageInfo

func (m *Prepare) GetView() uint64 {
	if m != nil {
		return m.View
	}
	return 0
}

func (m *Prepare) GetTxinfo() []*TransactionInfo {
	if m != nil {
		return m.Txinfo
	}
	return nil
}

type Commit struct {
	View                 uint64             `protobuf:"varint,1,opt,name=view,proto3" json:"view,omitempty"`
	Txinfo               []*TransactionInfo `protobuf:"bytes,2,rep,name=txinfo,proto3" json:"txinfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Commit) Reset()         { *m = Commit{} }
func (m *Commit) String() string { return proto.CompactTextString(m) }
func (*Commit) ProtoMessage()    {}
func (*Commit) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{14}
}

func (m *Commit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Commit.Unmarshal(m, b)
}
func (m *Commit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Commit.Marshal(b, m, deterministic)
}
func (m *Commit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Commit.Merge(m, src)
}
func (m *Commit) XXX_Size() int {
	return xxx_messageInfo_Commit.Size(m)
}
func (m *Commit) XXX_DiscardUnknown() {
	xxx_messageInfo_Commit.DiscardUnknown(m)
}

var xxx_messageInfo_Commit proto.InternalMessageInfo

func (m *Commit) GetView() uint64 {
	if m != nil {
		return m.View
	}
	return 0
}

func (m *Commit) GetTxinfo() []*TransactionInfo {
	if m != nil {
		return m.Txinfo
	}
	return nil
}

func init() {
	proto.RegisterType((*Message)(nil), "strc.Message")
	proto.RegisterType((*CommitFin)(nil), "strc.CommitFin")
	proto.RegisterType((*RequestAllData)(nil), "strc.RequestAllData")
	proto.RegisterType((*RequestData)(nil), "strc.RequestData")
	proto.RegisterType((*ProofConn)(nil), "strc.proofConn")
	proto.RegisterType((*ResponseData)(nil), "strc.ResponseData")
	proto.RegisterType((*Regist)(nil), "strc.Regist")
	proto.RegisterType((*AuthhashInfo)(nil), "strc.AuthhashInfo")
	proto.RegisterType((*AuthHash)(nil), "strc.AuthHash")
	proto.RegisterType((*Transaction)(nil), "strc.Transaction")
	proto.RegisterType((*Block)(nil), "strc.Block")
	proto.RegisterType((*PrePrepare)(nil), "strc.PrePrepare")
	proto.RegisterType((*TransactionInfo)(nil), "strc.TransactionInfo")
	proto.RegisterType((*Prepare)(nil), "strc.Prepare")
	proto.RegisterType((*Commit)(nil), "strc.Commit")
}

func init() { proto.RegisterFile("messages.proto", fileDescriptor_4dc296cbfe5ffcd5) }

var fileDescriptor_4dc296cbfe5ffcd5 = []byte{
	// 726 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0x7b, 0x6b, 0x13, 0x4b,
	0x14, 0xcf, 0x63, 0xb3, 0x49, 0x4e, 0xd2, 0xb4, 0x77, 0xb8, 0xb7, 0x84, 0xde, 0x0b, 0xb7, 0x8c,
	0x45, 0x2d, 0x6a, 0x0a, 0x95, 0x8a, 0x20, 0x88, 0x6d, 0xa5, 0x6c, 0x51, 0x41, 0x86, 0x20, 0xfe,
	0x27, 0xdb, 0xec, 0x64, 0x33, 0x34, 0xfb, 0x70, 0x77, 0x12, 0xb7, 0x1f, 0xc2, 0x6f, 0xe5, 0x27,
	0xf0, 0x13, 0xc9, 0x9c, 0xd9, 0xd9, 0x47, 0x2d, 0xa1, 0x7f, 0xf8, 0xdf, 0x79, 0xfc, 0x7e, 0xe7,
	0xcc, 0x79, 0xcc, 0x81, 0x51, 0xc0, 0xd3, 0xd4, 0xf5, 0x79, 0x3a, 0x89, 0x93, 0x48, 0x46, 0xc4,
	0x4a, 0x65, 0x32, 0xdb, 0xfb, 0xdf, 0x8f, 0x22, 0x7f, 0xc9, 0x8f, 0xd0, 0x76, 0xb5, 0x9a, 0x1f,
	0x49, 0x11, 0xf0, 0x54, 0xba, 0x41, 0xac, 0x61, 0xf4, 0x47, 0x1b, 0xba, 0x1f, 0x34, 0x93, 0x3c,
	0x80, 0x96, 0xcc, 0xc6, 0xcd, 0xfd, 0xe6, 0xe3, 0xc1, 0xf1, 0x5f, 0x13, 0xc5, 0x9f, 0x4c, 0x13,
	0x37, 0x4c, 0xdd, 0x99, 0x14, 0x51, 0xe8, 0x34, 0x58, 0x4b, 0x66, 0xe4, 0x10, 0xba, 0x71, 0xc2,
	0x63, 0x37, 0xe1, 0xe3, 0x16, 0x22, 0xb7, 0x34, 0xf2, 0xa3, 0x36, 0x3a, 0x0d, 0x66, 0xfc, 0xe4,
	0x18, 0x40, 0x89, 0x39, 0xba, 0x8d, 0xe8, 0x9d, 0x02, 0x5d, 0x12, 0x2a, 0x28, 0xf2, 0x10, 0xec,
	0x59, 0x14, 0x04, 0x42, 0x8e, 0x2d, 0xc4, 0x0f, 0x35, 0xfe, 0x1c, 0x6d, 0x4e, 0x83, 0xe5, 0x5e,
	0xf2, 0x1a, 0x46, 0x09, 0xff, 0xba, 0xe2, 0xa9, 0x3c, 0x5d, 0x2e, 0xdf, 0xba, 0xd2, 0x1d, 0x77,
	0x10, 0xff, 0xb7, 0xc6, 0xb3, 0x9a, 0xcf, 0x69, 0xb0, 0x5b, 0x68, 0x72, 0x02, 0x83, 0xdc, 0x82,
	0x64, 0xbb, 0x5a, 0x34, 0x2b, 0x1d, 0x4e, 0x83, 0x55, 0x71, 0xe4, 0x25, 0x0c, 0x13, 0x9e, 0xc6,
	0x51, 0x98, 0x72, 0xe4, 0x75, 0x91, 0x47, 0x0c, 0xaf, 0xf4, 0x38, 0x0d, 0x56, 0x43, 0x92, 0x03,
	0xb0, 0xdc, 0x95, 0x5c, 0x8c, 0x7b, 0xc8, 0x18, 0x69, 0xc6, 0xe9, 0x4a, 0x2e, 0x1c, 0x37, 0x5d,
	0x38, 0x0d, 0x86, 0x5e, 0xf2, 0x04, 0xba, 0xb3, 0x40, 0xc8, 0x0b, 0x11, 0x8e, 0xfb, 0x08, 0xdc,
	0xae, 0xd6, 0x7f, 0x21, 0xd4, 0x14, 0x0c, 0xe2, 0xac, 0x0f, 0xdd, 0xd8, 0xbd, 0x59, 0x46, 0xae,
	0x47, 0x0f, 0xa1, 0x5f, 0x40, 0xc8, 0x7f, 0xd0, 0xbf, 0x5a, 0x46, 0xb3, 0x6b, 0x15, 0x19, 0xc7,
	0x39, 0x64, 0xa5, 0x81, 0x3e, 0x85, 0x51, 0xbd, 0x3b, 0x64, 0x0f, 0x7a, 0x1e, 0x5f, 0x8b, 0x19,
	0xbf, 0xf4, 0x72, 0x78, 0xa1, 0xd3, 0x57, 0x30, 0xa8, 0xb4, 0x63, 0x13, 0x94, 0xec, 0x40, 0xfb,
	0x9a, 0xdf, 0xe0, 0x56, 0xf4, 0x99, 0x12, 0xe9, 0x23, 0xe8, 0xc7, 0x49, 0x14, 0xcd, 0xcf, 0xa3,
	0x30, 0x54, 0x54, 0x55, 0xe2, 0xc2, 0x3c, 0xaa, 0xc7, 0x0a, 0x9d, 0x52, 0x18, 0x56, 0x9b, 0x47,
	0x08, 0x58, 0x9e, 0x6a, 0xaf, 0x4e, 0x81, 0x32, 0xf5, 0xc0, 0x66, 0xdc, 0x17, 0xa9, 0x24, 0x2f,
	0x60, 0x68, 0x98, 0x97, 0xe1, 0x3c, 0xca, 0x37, 0x96, 0x94, 0x2d, 0x35, 0x1e, 0x56, 0xc3, 0x11,
	0x9a, 0x8f, 0xa0, 0x75, 0xd7, 0x08, 0xf4, 0x00, 0xe8, 0x67, 0x18, 0x56, 0x23, 0x6c, 0x2c, 0xb8,
	0x5a, 0x51, 0x6b, 0xbf, 0xad, 0x7c, 0x46, 0x57, 0xcd, 0x10, 0x5e, 0x86, 0x4b, 0xdf, 0x61, 0x4a,
	0xa4, 0x4b, 0xe8, 0x99, 0x5c, 0x45, 0x54, 0xef, 0x56, 0x54, 0xaf, 0x8c, 0xea, 0xe8, 0xa8, 0x4d,
	0x13, 0x15, 0x79, 0xbb, 0x60, 0xcb, 0xc8, 0xf7, 0x97, 0x3c, 0x0f, 0x9c, 0x6b, 0x2a, 0xdb, 0xa5,
	0x97, 0xe1, 0x97, 0xe9, 0x30, 0x25, 0xd2, 0x00, 0x06, 0x95, 0xbf, 0xab, 0x1a, 0x3a, 0xcd, 0x8a,
	0x64, 0x28, 0x2b, 0x1b, 0xee, 0xb0, 0x4e, 0x62, 0x99, 0xc6, 0x4f, 0x6f, 0x62, 0x13, 0x1e, 0xe5,
	0xa2, 0x6d, 0xd6, 0x86, 0xb6, 0xfd, 0x6c, 0x42, 0xe7, 0x4c, 0xad, 0x98, 0x8a, 0xb0, 0x28, 0xf7,
	0x0e, 0x65, 0x72, 0x00, 0x5b, 0x71, 0xc2, 0xd7, 0x67, 0xc5, 0x52, 0xea, 0x94, 0x75, 0x23, 0x39,
	0x81, 0xa1, 0x2c, 0x9f, 0x9c, 0x8e, 0xdb, 0xfb, 0xed, 0x3b, 0x0f, 0x11, 0xab, 0xc1, 0x54, 0x4f,
	0x1c, 0x2e, 0xfc, 0x85, 0xc4, 0x0b, 0xd0, 0x61, 0xb9, 0x46, 0xde, 0xc0, 0x96, 0xcf, 0x43, 0x9e,
	0xb8, 0x92, 0x7b, 0x53, 0x11, 0xf0, 0xfc, 0x8f, 0xef, 0x4d, 0xf4, 0x49, 0x9c, 0x98, 0x93, 0x38,
	0x99, 0x9a, 0x93, 0xc8, 0xea, 0x04, 0xfa, 0xbd, 0x09, 0x50, 0x1e, 0x2a, 0x55, 0xd9, 0x5a, 0xf0,
	0x6f, 0x58, 0x99, 0xc5, 0x50, 0xbe, 0x67, 0x65, 0xbb, 0x60, 0x2f, 0xf4, 0x13, 0xdb, 0xc8, 0xcd,
	0x35, 0xf2, 0x0c, 0x6c, 0x99, 0x09, 0xb5, 0xc2, 0x16, 0xd6, 0xfa, 0xcf, 0x6f, 0xb5, 0xe2, 0x16,
	0xe7, 0x20, 0x3a, 0x85, 0xed, 0x5b, 0x2e, 0x95, 0xbf, 0xd2, 0x0c, 0x61, 0x06, 0x5c, 0x37, 0x92,
	0x7f, 0xa1, 0x2f, 0xb3, 0x2f, 0x6b, 0x9e, 0x88, 0xb9, 0xfe, 0x9f, 0x3d, 0xd6, 0x93, 0xd9, 0x27,
	0xd4, 0xe9, 0x7b, 0xe8, 0x6e, 0xaa, 0xb0, 0x7c, 0x63, 0xeb, 0x3e, 0x6f, 0x7c, 0x07, 0xb6, 0x3e,
	0x44, 0x7f, 0x20, 0xd8, 0x95, 0x8d, 0x33, 0x7a, 0xfe, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x2d, 0x29,
	0x05, 0xc8, 0xdc, 0x06, 0x00, 0x00,
}
